config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  
  # get 'posts/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:new, :create]

  resources :posts do
    resources :comments, only: [:create]
  end  

  get '/users' => redirect('users/new')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  post_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  
  validates :title, :content, presence: true
  validates :content, length: {minimum:250}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_secure_password  # validations: false
    
    has_many :posts
    has_many :comments

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: {with: VALID_EMAIL_REGEX}
    validates :password, presence: true, on: :create
    validates :password, length: {minimum:8, maximum:20}, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def log_in(user)
        cookies.permanent.signed[:user_id] = user.id
        @current_user = user
    end

    def log_out
        cookies.delete(:user_id)
        @current_user = nil
    end

    private
        def signed_in?
            !current_user.nil?
        end
        helper_method :signed_in?
        
        def current_user
            @current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
            rescue ActiveRecord::RecordNotFound            
        end
        helper_method :current_user

        def private_access
            redirect_to :login unless signed_in?
        end

        def public_access
            redirect_to root_path if signed_in?
        end
        
            
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        post = Post.find(params[:post_id])
        post.comments.create(comments_params)
        flash[:info] = "Comentario creado"
        redirect_to post
    end

    private
        def comments_params
            params.require(:comment).permit(:body).merge(user: current_user)
        end
        
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :private_access, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save 
      flash[:success] = "Post publicado con éxito"
      redirect_to posts_path 
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Post modificado con éxito"
      redirect_to posts_path
    else
      render :edit
    end
  end
   
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:info] = "Post eliminado con éxito"
    redirect_to posts_path 
  end
    
  private
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :private_access, only: [:destroy]
  before_action :public_access, except: [:destroy]
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to root_path
    else
      flash.now[:danger] = 'Email y/o contraseña inválidos'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Super Blog!"
      redirect_to root_path
    else
      render :new    
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    class CodeRayify < Redcarpet::Render::HTML
        def block_code(code, language)
            CodeRay.scan(code, language).div
        end
    end

    def markdown(text)
        coderayified = CodeRayify.new(:filter_html => true, :hard_wrap => true)
            options = {
                :fenced_code_blocks => true,
                :no_intra_emphasis => true,
                :autolink => true,
                :strikethrough => true,
                :lax_html_blocks => true,
                :superscript => true
            }
        markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
        markdown_to_html.render(text).html_safe
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def form_title
        @post.new_record? ? "Crea un nuevo post" : "Editar post"
    end

    def form_submit
        @post.new_record? ? "Crear post" : "Actualizar post"
    end      
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/7eaa1e7418.js"></script>
  </head>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "SuperBlog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if signed_in? %>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
              Hola <%= current_user.name %>
            </a>
          </li>
          <li class="nav-item">
            <%= link_to 'Nuevo Post', new_post_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Salir', logout_path, method: :delete, class: 'nav-link'%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Ingresar', login_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Registrarse', new_user_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <% flash.each do |msg_type, msg|%>
    <div class="alert alert-<%= msg_type %> alert-dismissible fade show" role="alert"><%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1><%= form_title %></h1>
      <% if @post.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for @post do |f|%>
        <div class="form-group">
          <%= f.label :title, "Título" %>
          <%= f.text_field :title, class: "form-control input-lg", placeholder: "Ingresa el título del post" %>
        </div>
        <div class="form-group">
          <%= f.label :content, "Contenido (250 caracteres mínimo)" %>
          <%= f.text_area :content, class: "form-control", 
          placeholder: "Escribe tus ideas...", rows: 10, data: {provide: "markdown"}%>
        </div>
        <div>
          <%= f.submit form_submit, class: "btn btn-primary btn-block btn-lg"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 offset-sm-1 mt-3">
      <% if signed_in? %>
        <div class="text-right">
          <%= link_to 'Crea un nuevo Post', new_post_path,
         class: "btn btn-primary" %>
        </div>
      <% end %>
      <% @posts.each do |post| %>
        <h2 class="mt-3"><%= link_to markdown(post.title), post %></h2>
        <p class="publish_by">Publicado por <%= post.user.email %> <%= time_ago_in_words(post.created_at) %></p>
        <!-- <p><%= markdown(post.content.truncate(250)) %></p>-->
        <p><%= markdown(post.content.truncate(250)) %></p>
        <div class="mb-5">
          <% if signed_in? && current_user == post.user %>
            <%= link_to " editar" , edit_post_path(post), class: "far fa-edit"%>
            <%= link_to ' eliminar', post, method: :delete, data: {confirm: "¿Estas de acuerdo?"}, class: "pl-1 far fa-trash-alt" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1>Create a new Post</h1>
      <%= form_for @post do |f|%>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control input-lg", placeholder: "Enter your post's title" %>
        </div>
        <div class="form-group">
          <%= f.text_area :content, class: "form-control", 
          placeholder: "Type your thoughts", rows: 5, data: {provide: "markdown"}%>
        </div>
        <div>
          <%= f.submit "Publish your Post", class: "btn btn-primary btn-block btn-lg"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-sm-10 offset-sm-1">
      <%= link_to 'Volver', root_path %>
      <h1><%= markdown(@post.title) %></h1>
      <p class="mb-5"><%= markdown(@post.content) %></p>
      <div class="comments">
        <% @post.comments.each do |comment| %>
          <div class="card mb-3">
            <div class="card-header p-2">
              <span><%= comment.user.email %> comentó <%= time_ago_in_words(comment.created_at) %></span>
            </div>
            <div class="card-body p-2"><%= comment.body %></div>
          </div>
        <% end %>
        <% if signed_in? %>
          <h5 class="mt-3">Nuevo comentario</h5>
          <%= form_for [@post, @post.comments.build] do |f|%>
            <div class="form-group">
              <%= f.text_area :body, class: "form-control", placeholder: "Ingresa tu comentario"%>
            </div>
            <div class="actions mb-4">
              <%= f.submit "Comentar", class: "btn btn-primary" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1>Crea tu cuenta</h1>
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Nombre" %>
          <%= f.text_field :name, class: "form-control input-lg",
           placeholder: "Nombre" %>
        </div>
        <div class="form-group">
          <%= f.label :email, "Email" %>
          <%= f.email_field :email, class: "form-control input-lg",
           placeholder: "Email"%>
        </div>
        <div class="form-group">
          <%= f.label :password, "Contraseña (minimo 8 caracteres)" %>
          <%= f.password_field :password, class: "form-control input-lg",
           placeholder: "Contraseña" %>
        </div>
        <!--confirmation password feature-->
        <div class="form-group">
          <%= f.label :password_confirmation, "Confirmación contraseña" %>
          <%= f.password_field :password_confirmation, class: "form-control input-lg",
           placeholder: "Confirmación contraseña" %>
        </div>
        <!--end-->
        <div class="actions">
          <%= f.submit "Crear cuenta", class: "btn btn-primary btn-block btn-lg"%>
        </div>
      <% end %>
      <p><%= link_to "Login", login_path %></p>
    </div>
  </div>
</div>